hibernate.dialect= org.hibernate.dialect.MySQLDialect
hibernate.connection.driver_class = com.mysql.cj.jdbc.Driver
hibernate.show-sql = true
hibernate.hbm2ddl.auto = update
# Change 'localhost' to your server address and 'example' to your database name
hibernate.connection.url = jdbc:mysql://localhost/FinalProjectDB
# Change 'root' to your username
hibernate.connection.timezone=UTC
hibernate.connection.username = root
# Change 'password' to your password
hibernate.connection.password=1234
