# Hibernate dialect for MySQL
hibernate.dialect = org.hibernate.dialect.MySQLDialect

# JDBC driver for MySQL
hibernate.connection.driver_class = com.mysql.cj.jdbc.Driver

# Show SQL statements in logs
hibernate.show_sql = true

# Preserve existing data by updating the schema
hibernate.hbm2ddl.auto = update

# Database connection URL
hibernate.connection.url = jdbc:mysql://localhost/FinalProjectDB

# Timezone for database connection
hibernate.connection.timezone = UTC

# Database username
hibernate.connection.username = root

# Database password
hibernate.connection.password = 1234